spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.mysql:3306/memocode_question_server_prod
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.dev.memocode.dev

logging:
  level:
    org.springframework.transaction.interceptor: TRACE

custom:
  front:
    domain: "http://localhost:5173"
    domain2: "https://dev.memocode.dev"